dist: trusty
language: python
python:
- '2.7'
install:
- pip install ansible==2.7.1 molecule==2.19.0 apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: v5TO2iMd26JhNW1gHbJIMPf3EsDdHUFK2ezaWLzAeWir8sPnhb1Rzvo6zhGYfP0B/aDbIRgzFRTOKYCHqeldJEwv8mtVIZpp3AuUwx/H3kQIKfoA9/6Je5A2YWyv+ik1dCedmtcZHv74OplkzFkQiphWoxnnDJ8E775zVY1dbnljB5xAL4+jSk52rw1VB1RRZ24JCnrH76aIhCZKxN+nQTMKwLHDznsaYQxEI5IIMr7ESVWu7NOQSMnOLHstf9tATKMAdVf8ep4DqCHDX+k/o1gKW0xN3owAto296nhHxvJocAEa2brHmfgKLF0SwcbSMRMa5Q8/2Xern8NNBAVYSLxnhy6cXiPvsTyv5ds9oz5Ufl3Wyrcy94zpPWE8gTgEWDPSgqKKAKIo5hbLBzFCLmGmSb+jAS8rZFlQ/LGzCa3WqWKalRcfWueuQoIHPKgOJUMva65BkwNk/xMoVHBnRl6PdviVNIAd06vwEGTGtVPdJgvj8wTJABpxtetH5L2g+nYVJzpe77vZTFgb3l0OqC3h7JvHjWGnyUHSi/Ml/NTlIU4le6Fs8xLaUt/Imfs4b42wq3jQWcho6Tch412ZnmDMnR9yBl44Pj822PMQjv6FZe2I/CGRItIf7MCzo0KEMnF4LeeYgOzrwYYHNsD7+wH5EhgPQ60oHdO68ZhtiUE=
  - secure: oItAOWQ6gDjUph2LL8R8eG93/YGM7JxLk9olL6KlK+/AsTEPYBOrvLxB4Aq/SxsGW7+7stztDcJ9u77m01UvIVvtZxB1hnJ9+LNi1A/4hNXdA0nqUr6eEsvb9ymwOASho785e31Y5zQ2zGolxERom5LZcczXBSrxMS+KBQ/1WG8rubVsPrPRharj6O3H2eGscUkKm6xtop/FqfvuAaBqLeZrKG4xbrO4irpgOQKfw+L/eGvcXlUrLjUXtEqIb6UKGuxIKyogb7m/lXz9FDNh/oQPUmYkS82kZzXjY6xkjHJBhKfSK5yvnBGLNQVc25he0xL3oSKvqfOym3ofClGUTYv5CoCpLklPQQTYSceLjXjyc66hbPSd2rDX7JDOpLYd3SuhwasO6Zk0rAwBWxHfLAcfzuc31l1Q1QMQs9F97Imm0GI3UjCMh9tvuQKYXfkmZNKpEybbTKR6Bj+7EoFpr1DerePZBxQHQOzONWn44OY3bpTtmf5p7TrXbBYE3VYDQ0MMrAxLoXgSogLMpSEAScRB66lmhHhZ6ctNaVFlYdEgDEnaoqeYfwvOVo4srRzh2NXrhtsJVTsXJAs23sr/ya4nFw4s9ki+xcNx+6w+CzuxIKOuURZs67gax56Tnod1gYwMUJr3ysKGQg6n9C1SFxpJ5oUxdPIGFYVAdaWnE/w=
  - secure: MoxUEY1TXNGPDREIzI/Ot2fFa2xXKLhN8bTh4f6K0GKVAW86HkgWoKW35SmBpZ7RXkcUeA+LimG1kX3IuKhisMtKrcBVm47YoBrMjjrXHqsFjgkcAsYWKnAXXARk9Cbyb4+yarWbytTj1z2wCc+ZkM67OB4hs1n+Gwf5MH506AEKMwL8FrkPLPhxbXSb9D+y9rU3rxrz4iZ+4Iv0eGKGFjWSVcKumcrlI/LT0cXhuILhz+FA+C3Ma7ZhSOWq4mXa2KtNdg79clA4bHDWoymR5+Ua8Ayi/AloAOxOVs/SBarpnBE/rU0VIBCNa1MvWHO51Zrfi01VTMhUeE3uronl/ViLXO3s5ggrmty1OAVdJfx7ijmB4x23IHgtgYIspq6Z0mMXnhWWohLWGFsTwHs9CHY1vatAe2DQlluN/6hF4oXmOi2qZ9AU32IY9Hy0ol3sLEb1FvtgYw04llvN/42IIChRpPXg8PpnR1LVO35qnyiFBj6DMVLJrMD5MX51n+BGgfPYa9MZoHICFXbLU1PXKSlDvNu/KAP2ofON+pHfMjqDKK+Mf6wcdeJZmLqJY10rk9zAeYfJ1KuoKCFQKWo/UlJDEmNp1GTw+/nPYXmu5BX4Sgh6o5UVplnn79ddA7faGYOrRfgyLR6xTJ3lIx8D1gPEMOJGzWFqLocJ/RiaDBs=
before_install:
- openssl aes-256-cbc -K $encrypted_6d8931a32705_key -iv $encrypted_6d8931a32705_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo $GCE_CREDENTIALS_FILE
script:
- molecule --debug create
- molecule --debug converge
- molecule --debug verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: VEo6ulswal5IM7oZibz39cf1h0UkB9FDmfnJYLe94hH2ZiBJ3GF7gJAom3uUEXYi0lMm1DAnd7BsY3z3P46imNOnJ6LhWP0B2z2hQkOkrOXrVNfDaJ6WWmn2KU75RVIminPfaEL25uGl2jAG41MW1hMlFuNQCHM/l5bd1iEtK41OBMeFgD2nOcXSqU5s4lU4cD1pyVP2n9d+0v/KG74EeIqNjg1XWZ3cdPj3U18wIYaK/jZDAkra+OCEoLvmbGm3/WsVEgKTbDDdts3/YqGUDeCnrcPCZ+w/qRAuqvoizFNPAR1Y63PdBALRQ1Hm6zHME+wzH/JJO0UbdDKX4L4nMLBJs0Xa5E3u34n2PoZmlECIHqTZ2ofoASYPK3H0mKHjsYXPUrYHCo8JB2AM4YSz6bXMFzR6tVOAEMl4S3MqjwPJlpaLLNKvcE965ioU5l199yWxq0q/yF1puKKfaCJSgPP8FmsmXT/ik2kJANPRlRcDtsHOpbXrdz6w8BLHjJYm4fGvW5Ee8n8lTreq6h0MI6Vd67cikhuokBM5TjPjkQbLiNrT0qFiTbE4icX/bwqitMsSBJGXc34qVvYKKIooAOQYq164Zoj4+nPCJp2yKcjECH9WQXDRHJiAw2NqVEI3DtQIQnsxlMd/TpV6DHuf7An51E3L7BIq+YbzUKPrJKI=
