dist: trusty
language: python
python:
- '2.7'
install:
- pip install ansible==2.7.1 molecule==2.19.0 apache-libcloud pycrypto
env:
#  matrix:
#  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: GcKQA5rgGvHQCJ4nR1WUN+qaslA6N1q8G7smKk1BI8RGX+kILhLUET2COzt0CV4dDD9gGyAuRtmWQAbSOL19joMCHRXp+vuoC0JBOLo7BhAfT9+ArOfTWxU7aNybPSg1/+n6EOvnlsr5RpFzENMlu9R9zxxLoeHhErEghCtz5Onr1kY7e6HusD8BUtUvkA2OaZ6CsRJ0vkqgOoSvJ7wq+3SKfHVNTfCSBJ5NB4RZ2NJZsjPFF1Gj/V7zz+4vyNYMNIpui55svTrP9GALAul9wRgf80n+VXrLpaBm2+afDJId41HaGdjUXMVCF7+6m1HkPlEXC1So3PkfRPS0OHoPD4phwddpGs4Yz0/Ba/ir5WLe85Dnr4EK/3BvM5Y6iyjB0Rt7lZ9x/lXRp9WRmx4xBabXsKbgIUrIVPiENkJ1uM1a1C6B2oE98QMeRUIMgnELvrF/f+IfoQ+JgoqeYv9UtkKDpdBDFQv65+dTaakhZY3unpLqntgXAOWd+229LwIUJXAE0bLInk2xuoker6IeaB2u2/BcC1TzG4h22hJWsQejoecQWKHsQBGhsIaR2RXcl9io3qZ6C5AyHt/etKgUo+WvdtNyOG5Pc50J+YYrhk9vlcb/BKxQIW7mOhpiIWp9Aq7/t6wvmmOoG+Rl6U7LtBynS8QZldG/lgyNCZRBB04=
  - secure: hmr9YtNKZOrxDcf5wXL4wmyMdPi4v1724BenIgDG4/47dRjjXHmTfH3iB62cvkDxtYjsj/EEQ2eb1pWM6C0AdYeawrOo9JUdmH7B+v8xPb2IGVm4Lo3QeT93OxRp47AFMBKsd5k9HeB6Jg1E7ydtH7I5rebjkrLFZ7w1MEfHrwIEgNS6PnCdlZHd2zmfZdSU4JYRgSB4CefQsT0/ckzelp0lYSLU0koeG5XtdjKNhb4g+2eAXNoInEgzyMnPY/R9LUDn1LayFKXq4Fz+ezCef6BfMWlKAF+ybQfwf0tkzNQRfYglD20DWLiertbCOflc3QlZdZN6Dw0XlH5MTOjh/nSMNXB6x+WVY7ohJI/R0mweRO3hQXwhnSgKbLaNBRlsvrHDqUy6BGRmhTEmpF7S83mF8Xo+t5gqs49N1H7xJjWnvnEYdYU9SWklCXLbP9QpJHbnkUPIKFpFHVtXonwYvoGYcKxW6b5GfVIZDI2Qjyyhu9k2dV2CRXD4ogEJNdr06YCTr/gw/EgIsXxU4BQBbfQcPRHOueX1SP/62d9P9J9WI5SaDYhBAQzlHdUpomVquJK16boDuMaUc0pjp/o8j5GsD9uKRuoxZgXQkb4HScNzzUVVcGonrjulYGFX9iWeLJl3vjusvQhUAe5MWlKtOTaFZVETAgbJaQUhGNsmyTM=
  - secure: t0M1S6aYtsUsCiVBtEBVjDYfTKlB6OuI+t9nfQAxHqpSRVfnbGq6aJ0G6MEwfYGTEp9FC22lawD91MrpT1+7BYZYcbsXUh1Oji5Orv2VR+XEUfZad0icLRmVrgq95V2TClwZtKEKIejWQWwRXpSWBwlfBJYqJK5rTHKDwj5rRyXQMDWEi8PGZUW3u+8iKfegJTJe9cEn61Q5QtJbt0h7i8vvWZqk3IXkWfgDuqUk2RhO1vEMn8z0jpS4hddwnrLmdhEJ2BYFitN5Dww+aOUINsOOVEuEDdYReb5wlGCl3OU3xblUax3OTBvdqBS2ffoNHCZgdROknyo0oOotdwRLT4Mi3yoRbdFRJ44xcxxH9ztLxb1DyA1IdE/bYbJpXPGbPi5Dxbyu8O0yi4CoJTLSGH8JeM53Ug+27AoCXBaNL2eC3YhZAgbnmE/4m1T5cMh1mACzWQ3S3OmaFYlVcddGNKL3cWXU1YvpfQ5voLDCza7zBWffD9yVSdyAT7o3gA8HbHg/ZWlnCFew0W4CvcOspW7HCo8c/H+fV+jMMgFcNIfOnIDSN2Aw/zxeEjklPUnOOwWB726KYpuPscFcJLPrjQYSqcg4NJ5Vl92XMolZbKMfOL+exRKUuZF0fxnOIf/4TUzRP1zzYVFaP/2kCpY/cN87ArL3mKykqBsuBQ/8/9M=
before_install:
- openssl aes-256-cbc -K $encrypted_6d8931a32705_key -iv $encrypted_6d8931a32705_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo $GCE_CREDENTIALS_FILE
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: VEo6ulswal5IM7oZibz39cf1h0UkB9FDmfnJYLe94hH2ZiBJ3GF7gJAom3uUEXYi0lMm1DAnd7BsY3z3P46imNOnJ6LhWP0B2z2hQkOkrOXrVNfDaJ6WWmn2KU75RVIminPfaEL25uGl2jAG41MW1hMlFuNQCHM/l5bd1iEtK41OBMeFgD2nOcXSqU5s4lU4cD1pyVP2n9d+0v/KG74EeIqNjg1XWZ3cdPj3U18wIYaK/jZDAkra+OCEoLvmbGm3/WsVEgKTbDDdts3/YqGUDeCnrcPCZ+w/qRAuqvoizFNPAR1Y63PdBALRQ1Hm6zHME+wzH/JJO0UbdDKX4L4nMLBJs0Xa5E3u34n2PoZmlECIHqTZ2ofoASYPK3H0mKHjsYXPUrYHCo8JB2AM4YSz6bXMFzR6tVOAEMl4S3MqjwPJlpaLLNKvcE965ioU5l199yWxq0q/yF1puKKfaCJSgPP8FmsmXT/ik2kJANPRlRcDtsHOpbXrdz6w8BLHjJYm4fGvW5Ee8n8lTreq6h0MI6Vd67cikhuokBM5TjPjkQbLiNrT0qFiTbE4icX/bwqitMsSBJGXc34qVvYKKIooAOQYq164Zoj4+nPCJp2yKcjECH9WQXDRHJiAw2NqVEI3DtQIQnsxlMd/TpV6DHuf7An51E3L7BIq+YbzUKPrJKI=
